# Generated by Django 4.2.3 on 2023-07-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_rename_coloritem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color_id',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(to='MainApp.color'),
        ),
    ]
